version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10  
    commands:
      - aws cloudformation package --template-file template.yaml --s3-bucket app-compucloud-zip --output-template-file outputSamTemplate.yaml
artifacts:
  files:
    - 'outputSamTemplate.yaml'
    - 'template.yaml'